api_platform:
    title: URLShortify
    version: 1.0.0
    description: Manage your with URLShortify.
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header