version: '3'

services:
    database:
        image: 'mysql:8.0'
        container_name: shortify_database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db_shortify
        ports:
            - '3306:3306'
        networks:
            - shortify_net

    phpmyadmin:
        image: phpmyadmin
        container_name: shortify_phpmyadmin
        depends_on:
            - database
        restart: unless-stopped
        environment:
            PMA_HOST: database
        ports:
            - '8181:80'
        networks:
            - shortify_net

networks:
    shortify_net:

volumes:
    db-data: