version: '3'

services:
  mailer:
    image: schickling/mailcatcher
    container_name: shortify_mailcatcher
    ports: ['49695:1025', '49378:1080']
    networks:
      - shortify_net
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
